spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    app.askresume: info

# Swagger 설정
swagger:
  title: "ask-resume API DOCS (운영)"
  description: "운영서버 API 문서입니다."