spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    app.askresume: debug # todo 패키지 수정

# JWT Token 설정 // 개발환경 인증 편하게 하기 위해
token:
  access-token-expiration-time: 9999999999999
  refresh-token-expiration-time: 9999999999999

# Swagger 설정
swagger:
  title: "ask-resume API DOCS (로컬)"
  description: "로컬서버 API 문서입니다."

oauth:
  domain: localhost
  client-home: http://localhost:4000
  providers:
    google:
      redirect-url: http://localhost:8080/api/oauth/google/callback
    linked-in:
      redirect-url: http://localhost:8080/api/oauth/linked-in/callback

# Actuator Config
management:
  endpoint:
    web:
      exposure:
        include: "*"