server:
  port: 8080
  servlet:
    context-path: /

spring:
  jpa:
    show-sql: true # 콘솔창에 SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL 예쁘게 출력
        default_batch_fetch_size: 1000 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 3MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 3MB # 파일 업로드 요청 시 모든 파일 크기합을 10MB 제한

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

file:
  licensed:
    content: application/pdf

# logging 설정
logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    app.askresume: debug

# spring cloud feign client 설정
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Swagger 설정
swagger:
  version: "1.1"

# JWT Token 설정
token:
  secret: ENC(Asav0xGGT30Lonv8yKqEEHmjJ+7poB/DKfApzEBD7/xg1mFS/PJOQP5k1Lx1JYND)
  access-token-expiration-time: 900000  # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

# Jasypt password 설정
jasypt:
  encryptor:
    password: ${PASSWORD}

# 구글 API 설정
google:
  client:
    id: ENC(xx8p5eq2h6I2vjNtzVMIvfAH33RIazne1T5Jec02s1ftfxrDdbNmQSN9q4ZFu2HvqIu2IOkR1BsqBRE40IqSTRC6JjSoYUss/MZqFA6QJpumqpNJzGeXig==)
    secret: ENC(mgRSuQYDp4hS0tLFLE/6V0O6BMwrLrWf+ofHghuWW1tFWuhFB9wsYqdQ4vxafgdV)


# 외 다른 내용은 GptConfig 에서 수정
openai:
  token: ENC(u+JMfzA9xvOMFeZCHq/xSiGUfcnyd1Q57AK8B+7sL2AAXlwhXB881nTkcWSZkXYX4jYkjG0qHwjIq4dNue+5gA==)