spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded

logging:
  level:
    app.askresume: debug

# JWT Token 설정 // 개발환경 인증 편하게 하기 위해
token:
  access-token-expiration-time: 9999999999999
  refresh-token-expiration-time: 9999999999999

oauth:
  domain: localhost
  client-home: http://localhost:4000
  providers:
    google:
      redirect-url: http://localhost:8080/api/oauth/google/callback
    linked-in:
      redirect-url: http://localhost:8080/api/oauth/linked-in/callback

# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "metrics"
          - "prometheus"