

spring:
  datasource:
    url: ENC(K3MI1SHMCh6yPjfQqvutuBkdjTaL5nErdT3ieJm1YbdywWgKJqD6OWzFA5gM7fbLBFll2Kg+OQVWGpzFXf+hyzbvN2PRV8V5tht5ENqBq95DtLO5se4uIcK6mjLwIVOr/u7UE4CWuwyFtetKUJ7y12FMzDWpqUsFoOuICnWszYiBs/kqmxpSaQ==)
    username: ENC(QG90JJ2vRU3xjEpv/HkjhBiIpwXF0Ofr)
    password: ENC(mdL5KV+TXIE4izGxMfrvKduAXsqmeQYmYJSzTjHQYCPTqBXc/Ojy12UlmocnPr163JglsTCGxa8=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

logging:
  level:
    app.askresume: info

oauth:
  domain: ask-resume.com
  client-home: https://ask-resume.com
  providers:
    google:
      redirect-url: https://ask-resume.com/api/oauth/google/callback
    linked-in:
      redirect-url: https://ask-resume.com/api/oauth/linked-in/callback


# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "metrics"
          - "prometheus"