spring:
  datasource:
    url: ENC(3chkk+LvuYxJqKjD6ly1f9brtSbkYazTWemsurxpnWLCkou4kzTRHQo7y+GSGEaB7JauoaEJEy6sbRtsVg4sfRy0SgJ3nlwPO7XNVs3wOK3Q8EL0lABAv8+ggCm3L9ViT4p9hW7oI3bSyxGTorgEHwxYNHB9rjvJRVPdMI7mBJ4K0gn+xUaNWQ==)
    username: ENC(EY2UjrJjPFCehvVShq8aOA==)
    password: ENC(L/1/2wgCwnq+qDZSYeM7bePmgZa3jchPZZp2kfAW9Bk=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    app.askresume: debug

oauth:
  domain: localhost
  client_home: http://localhost:4000
  providers:
    google:
      redirect-url: http://dev.ask-resume.com/api/oauth/google/callback
    linked-in:
      redirect-url: http://dev.ask-resume.com/api/oauth/linked-in/callback

# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "metrics"
          - "prometheus"