spring:
  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/ask-resume?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect


# Swagger 설정
swagger:
  title: "ask-resume API DOCS (로컬)"
  description: "로컬서버 API 문서입니다."